### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by gerrywastaken** [AbnerRico/LinkedInOpenAIResponses#1]
This looks quite interesting but I'm wondering how you are fetching this file:
https://github.com/AbnerRico/LinkedInOpenAIResponses/blob/master/app/app.py#L10

**Comment by AbnerRico** [comment]
> This looks quite interesting but I'm wondering how you are fetching this file:
> 
> https://github.com/AbnerRico/LinkedInOpenAIResponses/blob/master/app/app.py#L10

You can download your personal information from LinkedIn in the settings and privacy menu. They send you an email with a link to the file that contains all your inbox messages in csv format.
